name: golangci-lint

on:
  push:
  pull_request:
  schedule:
    - cron: '6 15 * * SUN'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
