name: modver

on:
  pull_request:

permissions:
  contents: read # This gets granted by default, so keep granting it.
  packages: read # This gets granted by default, so keep granting it.
  pull-requests: write # Needed to comment on the PR.

jobs:
  modver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: bobg/modver@f646e42936f006762d533d8dae3908cb7065adc9 # 2.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
